### ISSUE TITLE
Tracking issue for `Sable.` API's

### ISSUE THREAD

**Issue by Im-Beast** [sableland/sable#6]
### Currently planned API's:
this list should be expanded upon on the fly

`Sable.`
 - `fs`
   - [x] `readFile` – read file and return `Uint8Array`
   - [x] `readTextFile` – read file and return `string`
   - [x] `writeFile` – write file using `Uint8Array`
   - [x] `writeTextFile` – write file using `string`
   - [x] `removeFile` - delete file
   - [x] `removeDirectory` - delete directory
   - [ ] `copyFile` - copy file
   - [ ] `copyDirectory` - copy directory
   - [ ] `moveFile` - move/rename file
   - [ ] `moveDirectory` - move/rename directory
   - [ ] `makeDirectory` - create a new directory
   - [ ] `makeFile` - create a new file
   - [ ] `makeTempDirectory` - create a new temporary directory in `/tmp`
   - [ ] `makeTempFile` - create a new temp file in `/tmp`
   - [ ] `watch` - create iterable which yields changes in file system
 - `io`
   - [x] `read` – read from resource id into given `Uint8Array`
   - [x] `write` – async write to resource id using `Uint8Array`
   - [x] `stdin` – interface for working with standard input
   - [x] `stdout` – interface for working with standard output
   - [x] `stderr` – interface for working with standard error output
 - `testing`
   - [x] `test` - test runner
   - [x] `bench` - benchmark runner

**Comment by Im-Beast** [comment]
Things that are yet to be discussed:
 - `Sable.fs.File`
 - `Sable.io.{Stdin, Stdout, Stderr}`
 - `Sable.io.{write, writeSync, read, readSync}` – should they even exist?
